title: WeaxMe
email: weaxme@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Блог юзера WeaxMe
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WeaxMe

# Build settings
markdown: kramdown
theme: minima


minima:
  date_format: "%d-%m-%Y"
